[workspace]

members = [
  "frontend", "frontend/src-tauri", "rpn",
]

# keywords = [ "RPN", "calculator", "tauri" ]
# categories = [ "mathematics", "science", "wasm" ]

resolver = "2"

# Copyright see AUTHORS & LICENSE; SPDX-License-Identifier: ISC+:w
